apiVersion: v1
kind: Service
metadata:
  name: managed-identity-wallets-local-lb
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      name: miw
    - port: 8081
      targetPort: 80
      name: keycloak
    - port: 5432
      targetPort: 5432
      name: postgres
    - port: 8086
      targetPort: 8086
      name: revocation
  selector:
    app: catenax-managed-identity-wallets