apiVersion: v1
kind: Service
metadata:
  name: {{ include "edc-controlplane.fullname" . }}
  labels:
    {{- include "edc-controlplane.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8181
      targetPort: default
      protocol: TCP
      name: http
    - port: 9090
      targetPort: metrics
      protocol: TCP
      name: metrics
    - port: 8282
      targetPort: ids
      protocol: TCP
      name: ids
  selector:
    {{- include "edc-controlplane.selectorLabels" . | nindent 4 }}
