apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "txdc.controlplane.fullname" . }}
  labels:
    {{- include "txdc.controlplane.labels" . | nindent 4 }}
spec:
  {{- if not .Values.controlplane.autoscaling.enabled }}
  replicas: {{ .Values.controlplane.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "txdc.controlplane.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.controlplane.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "txdc.controlplane.selectorLabels" . | nindent 8 }}
        {{- include .Values.controlplane.podLabels . }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "txdc.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.controlplane.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.controlplane.securityContext | nindent 12 }}
          {{- if .Values.controlplane.image.repository }}
          image: "{{ .Values.controlplane.image.repository }}:{{ .Values.controlplane.image.tag | default .Chart.AppVersion }}"
          {{- else if .Values.controlplane.postgresql.enabled and .Values.vault.azure.enabled }}
          image: "ghcr.io/catenax-ng/product-edc/edc-controlplane-postgresql-hashicorp-vault:{{ .Values.controlplane.image.tag | default .Chart.AppVersion }}"
          {{- else if .Values.controlplane.postgresql.enabled and .Values.vault.azure.enabled }}
          image: "ghcr.io/catenax-ng/product-edc/edc-controlplane-postgresql-vault:{{ .Values.controlplane.image.tag | default .Chart.AppVersion }}"
          {{- else if .Values.vault.hashicorp.enabled }}
          image: "ghcr.io/catenax-ng/product-edc/edc-controlplane-memory-hashicorp-vault:{{ .Values.controlplane.image.tag | default .Chart.AppVersion }}"
          {{- else if .Values.vault.azure.enabled }}
          image: "ghcr.io/catenax-ng/product-edc/edc-controlplane-memory:{{ .Values.controlplane.image.tag | default .Chart.AppVersion }}"
          {{- else }}
          {{- fail "cannot choose control-plane image automatically based on configuration" }}
          {{- end }}
          imagePullPolicy: {{ .Values.controlplane.image.pullPolicy }}
          ports:
          {{- range .Values.controlplane.endpoints }}
            - name: {{ . }}
              containerPort: {{ .port }}
              protocol: TCP
          {{- end }}
          {{- if .Values.controlplane.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.controlplane.endpoints.default.path }}/check/liveness
              port: {{ .Values.controlplane.endpoints.default.port }}
            initialDelaySeconds: {{ .Values.controlplane.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.controlplane.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.controlplane.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.controlplane.livenessProbe.failureThreshold }}
            successThreshold: {{ .Values.controlplane.livenessProbe.successThreshold }}
          {{- end }}
          {{- if .Values.controlplaneplane.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.controlplane.endpoints.default.path }}/check/readiness
              port: {{ .Values.controlplane.endpoints.default.port }}
            initialDelaySeconds: {{ .Values.controlplane.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.controlplane.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.controlplane.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.controlplane.readinessProbe.failureThreshold }}
            successThreshold: {{ .Values.controlplane.readinessProbe.successThreshold }}
          {{- end }}
          resources:
            {{- toYaml .Values.controlplane.resources | nindent 12 }}
          env:
            {{- if .Values.controlplane.debug.enabled and .Values.controlplane.debug.suspendOnStart }}
            - name: JAVA_TOOL_OPTIONS
              value: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address="{{ .Values.controlplane.debug.port }}
            {{- else if .Values.controlplane.debug.enabled }}
            - name: JAVA_TOOL_OPTIONS
              value: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address="{{ .Values.controlplane.debug.port }}
            {{- end }}

            ########################
            ## DAPS CONFIGURATION ##
            ########################

            # see extension https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/tree/main/extensions/iam/oauth2/oauth2-core
            - name: EDC_OAUTH_CLIENT_ID
              value: {{ .Values.daps.clientId }}
            - name: EDC_OAUTH_PROVIDER_JWKS_URL
              value: {{ printf "https://%s%s" .Values.daps.host .Values.daps.paths.jwks }}
            - name: EDC_OAUTH_TOKEN_URL
              value: {{ printf "https://%s%s" .Values.daps.host .Values.daps.paths.token }}
            - name: EDC_OAUTH_PRIVATE_KEY_ALIAS
              value: {{ .Values.vault.secretNames.dapsPrivateKey }}
            - nameEDC_OAUTH_PUBLIC_KEY_ALIAS: {{ .Values.vault.secretNames.dapsPublicKey }}

            #############
            ## GENERAL ##
            #############
            - name: IDS_WEBHOOK_ADDRESS
              value: {{ include "txdc.controlplane.url.ids" }}
            - name: EDC_IDS_ENDPOINT
              value: {{ include "txdc.controlplane.url.ids" }}
            - name: EDC_IDS_ENDPOINT_AUDIENCE
              value: {{ printf "https://%s%s" (include "control.host") "/api/v1/ids/data" }}
            - name: EDC_IDS_ID
              value: {{ .Values.controlplane.internationalDataSpaces.id }}
            - name: EDC_IDS_DESCRIPTION
              value: {{ .Values.controlplane.internationalDataSpaces.description }}
            - name: EDC_IDS_TITLE
              value: {{ .Values.controlplane.internationalDataSpaces.title }}
            - name: EDC_IDS_MAINTAINER
              value: {{ .Values.controlplane.internationalDataSpaces.maintainer }}
            - name: EDC_IDS_CURATOR
              value: {{ .Values.controlplane.internationalDataSpaces.curator }}
            - name: EDC_IDS_CATALOG_ID
              value: {{ .Values.controlplane.internationalDataSpaces.catalogId }}

            {{- if .Values.postgresql.enabled }}
            ################
            ## POSTGRESQL ##
            ################

            # see extension https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/tree/main/extensions/control-plane/store/sql/asset-index-sql
            - name: EDC_DATASOURCE_ASSET_NAME
              value: asset
            - name: EDC_DATASOURCE_ASSET_USER
              value: {{ .Values.postgresql.auth.username }}
            - name: EDC_DATASOURCE_ASSET_PASSWORD
              value: {{ .Values.postgresql.auth.password }}
            - name: EDC_DATASOURCE_ASSET_URL
              value: {{ printf "jdbc:postgresql://%s:%s/%s" .Values.postgresql.host .Values.postgresql.port .Values.postgresql.database }}

            # see extension https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/tree/main/extensions/control-plane/store/sql/contract-definition-store-sql
            - name: EDC_DATASOURCE_CONTRACTDEFINITION_NAME
              value: contractdefinition
            - name: EDC_DATASOURCE_CONTRACTDEFINITION_USER
              value: {{ .Values.postgresql.auth.username }}
            - name: EDC_DATASOURCE_CONTRACTDEFINITION_PASSWORD
              value: {{ .Values.postgresql.auth.password }}
            - name: EDC_DATASOURCE_CONTRACTDEFINITION_URL
              value: {{ printf "jdbc:postgresql://%s:%s/%s" .Values.postgresql.host .Values.postgresql.port .Values.postgresql.database }}

            # see extension https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/tree/main/extensions/control-plane/store/sql/contract-negotiation-store-sql
            - name: EDC_DATASOURCE_CONTRACTNEGOTIATION_NAME
              value: contractnegotiation
            - name: EDC_DATASOURCE_CONTRACTNEGOTIATION_USER
              value: {{ .Values.postgresql.auth.username }}
            - name: EDC_DATASOURCE_CONTRACTNEGOTIATION_PASSWORD
              value: {{ .Values.postgresql.auth.password }}
            - name: EDC_DATASOURCE_CONTRACTNEGOTIATION_URL
              value: {{ printf "jdbc:postgresql://%s:%s/%s" .Values.postgresql.host .Values.postgresql.port .Values.postgresql.database }}

            # see extension https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/tree/main/extensions/control-plane/store/sql/policy-store-sql
            - name: EDC_DATASOURCE_POLICY_NAME
              value: policy
            - name: EDC_DATASOURCE_POLICY_USER
              value: {{ .Values.postgresql.auth.username }}
            - name: EDC_DATASOURCE_POLICY_PASSWORD
              value: {{ .Values.postgresql.auth.password }}
            - name: EDC_DATASOURCE_POLICY_URL
              value: {{ printf "jdbc:postgresql://%s:%s/%s" .Values.postgresql.host .Values.postgresql.port .Values.postgresql.database }}

            # see extension https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/tree/main/extensions/control-plane/store/sql/transfer-process-store-sql
            - name: EDC_DATASOURCE_TRANSFERPROCESS_NAME
              value: transferprocess
            - name: EDC_DATASOURCE_TRANSFERPROCESS_USER
              value: {{ .Values.postgresql.auth.username }}
            - name: EDC_DATASOURCE_TRANSFERPROCESS_PASSWORD
              value: {{ .Values.postgresql.auth.password }}
            - name: EDC_DATASOURCE_TRANSFERPROCESS_URL
              value: {{ printf "jdbc:postgresql://%s:%s/%s" .Values.postgresql.host .Values.postgresql.port .Values.postgresql.database }}
            {{- end }}

            ################
            ## DATA PLANE ##
            ################

            # see extension https://github.com/catenax-ng/product-edc/tree/develop/edc-extensions/dataplane-selector-configuration
            - name: EDC_DATAPLANE_SELECTOR_SOKRATESPLANE_URL
              value: {{ printf "http://%s%s" (include "data.host.control") .Values.dataplane.endpoints.control.path }}
            - name: EDC_DATAPLANE_SELECTOR_SOKRATESPLANE_SOURCETYPES
              value: HttpData
            - name: EDC_DATAPLANE_SELECTOR_SOKRATESPLANE_DESTINATIONTYPES
              value: HttpProxy
            - name: EDC_DATAPLANE_SELECTOR_SOKRATESPLANE_PROPERTIES
              value: {{ printf "{ \"publicApiUrl\": \"https://%s\" }" (printf "%s%s" (include "data.host.public") .Values.dataplane.endpoints.public.path) }}

            # see extension https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/tree/main/extensions/control-plane/data-plane-transfer
            - name: EDC_TRANSFER_PROXY_ENDPOINT
              value: {{ printf "https://%s%s" (include "data.host.public") .Values.dataplane.endpoints.public.path }}
            - name: EDC_TRANSFER_PROXY_TOKEN_SIGNER_PRIVATEKEY_ALIAS
              value: {{ .Values.vault.secretNames.transferProxyTokenSignerPrivateKey }}
            - name: EDC_TRANSFER_PROXY_TOKEN_VERIFIER_PUBLICKEY_ALIAS
              value: {{ .Values.vault.secretNames.transferProxyTokenSignerPublicKey }}

            # see extension https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/tree/main/extensions/control-plane/http-receiver
            - name: EDC_RECEIVER_HTTP_ENDPOINT
              value: {{ .Values.backendService.httpProxyTokenReceiverUrl }}

            ###########
            ## VAULT ##
            ###########

            {{- if .Values.vault.hashicorp.enabled }}

            # see extension https://github.com/catenax-ng/product-edc/tree/develop/edc-extensions/hashicorp-vault
            - name: EDC_VAULT_HASHICORP_URL
              value: {{ printf "http://%s" .Values.vault.hashicorp.host }}
            - name: EDC_VAULT_HASHICORP_TOKEN
              value: {{ .Values.vault.hashicorp.token }}
            - name: EDC_VAULT_HASHICORP_TIMEOUT_SECONDS
              value: {{ .Values.vault.hashicorp.timeout }}
            - name: EDC_VAULT_HASHICORP_HEALTH_CHECK_ENABLED
              value: {{ .Values.vault.hashicorp.healthCheck.enabled }}
            - name: EDC_VAULT_HASHICORP_HEALTH_STANDBY_OK
              value: {{ .Values.vault.hashicorp.healthCheck.standbyOk }}
            - name: EDC_VAULT_HASHICORP_API_SECRET_PATH
              value: {{ .Values.vault.hashicorp.paths.secret }}
            - name: EDC_VAULT_HASHICORP_API_HEALTH_CHECK_PATH
              value: {{ .Values.vault.hashicorp.paths.secret }}

            {{- end }}

            {{- if .Values.vault.azure.enabled }}

            - name: EDC_VAULT_CLIENTID
              value: {{ .Values.vault.azure.client }}
            - name: EDC_VAULT_TENANTID
              value: {{ .Values.vault.azure.tenant }}
            - name: EDC_VAULT_NAME
              value: {{ .Values.vault.azure.name }}
            - name: EDC_VAULT_CLIENTSECRET
              value: {{ .Values.vault.azure.secret }}
            - name: EDC_VAULT_CERTIFICATE
              value: {{ .Values.vault.azure.certificate }}

            {{- end }}

            #####################
            ## DATA ENCRYPTION ##
            #####################

            # see extension https://github.com/catenax-ng/product-edc/tree/develop/edc-extensions/data-encryption
            - name: EDC_DATA_ENCRYPTION_KEYS_ALIAS
              value: {{ .Values.vault.secretNames.transferProxyTokenEncryptionAesKey }}
            - name: EDC_DATA_ENCRYPTION_ALGORITHM
              value: AES

      {{- with .Values.controlplane.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.controlplane.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.controlplane.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
