---

###########
# Install #
###########
install:
  postgresql: true
  vault: true
  minio: true
  backendservice: true

###################
# Backend Service #
###################
backend:
  fullnameOverride: "backend"
  service:
    type: NodePort
    frontend:
      port: 8080
    backend:
      port: 8081

##############
# PostgreSQL #
##############
plato-postgresql:
  fullnameOverride: "plato-postgresql"
  primary:
    persistence:
      enabled: false
  readReplicas:
    persistence:
      enabled: false
  auth:
    database: "edc"
    username: "user"
    password: "password"
sokrates-postgresql:
  fullnameOverride: "sokrates-postgresql"
  primary:
    persistence:
      enabled: false
  readReplicas:
    persistence:
      enabled: false
  auth:
    database: "edc"
    username: "user"
    password: "password"

#########
# MINIO #
#########
minio:
  fullnameOverride: minio
  replicas: 2
  drivesPerNode: 0
  serviceAccount:
    create: false
  persistence:
    size: 128Mi
  resources:
    requests:
      memory: 128Mi
  service:
    type: NodePort
    control:
      port: 9000
  users:
    - accessKey: platoqwerty123
      secretKey: platoqwerty123
      policy: customBucketPolicy
    - accessKey: sokratesqwerty123
      secretKey: sokratesqwerty123
      policy: customBucketPolicy
  buckets:
    # in some cases the minio API acts strange if there exists no bucket at all
    - name: dummybucket
      policy: none
      purge: true
  policies:
    - name: customBucketPolicy
      statements:
        - resources:
            - 'arn:aws:s3:::*'
          actions:
            - "s3:PutObject"
            - "s3:ListBucket"
            - "s3:CreateBucket"
            - "s3:GetObject"
            - "s3:DeleteObject"
            - "s3:DeleteBucket"

#########
# VAULT #
#########
vault:
  fullnameOverride: "vault"
  injector:
    enabled: false
  server:
    dev:
      enabled: true
      devRootToken: "root"
    # Must be the same certificate that is configured in section 'ids-daps'
    postStart:
      - "sh"
      - "-c"
      - |
        { 
        
        sleep 5

        }

  ui:
    enabled: true
    externalPort: 8200
    targetPort: 8200
