---
name: "Business Tests"

on:
  push:
    branches:
      - main
      - develop
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      ##############
      ### Set-Up ###
      ##############
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Login to Github Packages
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CXNG_GHCR_PAT }}
      - name: Use specific edc version via git submodule # due to lack of release versions in maven central
        run: |-
          [ ! -d "edc" ] && git submodule add https://github.com/eclipse-dataspaceconnector/DataSpaceConnector.git edc
          git submodule update --init
          git -C edc fetch --all
          git -C edc checkout 045c9a6c1f8dcde78dfcb0480cf49643cdb65401
      - name: Set up JDK 11
        uses: actions/setup-java@v3.1.1
        with:
          java-version: "11"
          distribution: "adopt"
          cache: "maven"
      - name: Build edc with Gradle to get latest snapshots
        run: ./gradlew publishToMavenLocal
        working-directory: edc
      - name: Start minikube
        id: minikube
        uses: medyagh/setup-minikube@master

      #################################
      ### install test environment ###
      #################################
      - name: Install test environment
        run: |-
          cd edc-tests/src/main/resources/deployment/helm/all-in-one
          helm install test-environment .
      - name: wait for control planes ready
        run: |
          minikube kubectl -- wait --for=condition=ready pod -l app.kubernetes.io/name=plato-edc-controlplane
          minikube kubectl -- wait --for=condition=ready pod -l app.kubernetes.io/name=sokrates-edc-controlplane
          minikube kubectl -- port-forward service/plato-edc-controlplane 8181 &
          minikube kubectl -- port-forward service/sokrates-edc-controlplane 9191 &

      ##########################
      ### Run Business Tests ###
      ##########################
      - name: run tests
        run: ./mvnw --am --projects edc-qa/business-tests test -Dtest="RunCucumberTest"
        env:
          CONNECTOR_A_DATA_MGMT_URL: http://localhost:8181/data
